export {default as HomePage} from './HomePage'
export {default as ArticleDetailPage} from './ArticleDetailPage'
export {default as LoginPage} from './LoginPage'
export {default as ProfilePage} from './ProfilePage'
export {default as RegisterPage} from './RegisterPage'
export {default as EditorPage} from './EditorPage'
