export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as WhatGPTkill} from './WHATGPTkill/WhatGPTkill'
export {default as Possibility} from './possibility/Possibility'
export {default as Features} from './features/Features'
